### ISSUE TITLE
Not Using GPU

### ISSUE THREAD

**Issue by PNeelkanth16** [Comfy-Org/Nvidia_RTX_Nodes_ComfyUI#17]
I am super excited with the quality of output but the problem is it's using my RAM. Not Using GPU for processing. Any thing that I'm missing on?

**Comment by raffetazarius** [comment]
This seems to be affecting me too.  My RAM (64MB) gets filled up and computer grinds to a halt doing anything else, but my 5090 VRAM only has 1GB used, and low GPU activity.

**Comment by jovan2009** [comment]
It's a video upscaling we are talking about? Because I would say it's normal for the RAM to be filled up with the processed video frames, depending on their number and resolution. (Like with any upscaling - or processing for that matter)

**Comment by raffetazarius** [comment]
But only 2-5% GPU activity, and minimal use of VRAM? Maybe I'm mistaken, but I expected this upscaler to work similarly to other upscalers (SeedVR2, and ESRGAN ones) and maximize usage of the GPU to provide the best speed and performance (especially since it's an Nvidia-engineered solution). 

I've come across other threads mentioning nvidia-vfx not installing correctly when you install the Custom Nodes in Comfy, but in my case, this Python lib was installed correctly first time - I triple-checked it guided by Gemini Pro.

**Comment by jovan2009** [comment]
This node in particular I think it doesn't use a lot of VRAM, it resizes one frame at a time and probably it's not a lot VRAM needed. But storing the processed frames takes a lot of RAM because they are stored uncompressed until they are saved to disk, either as individual images or a compressed video, depending on your workflow. Long story short the RAM you have limits the length and the resolution of what video you can process at one time in ComfyUI in general. You need to think strategies around that limitation, either lowering the resolution or limiting the length of the video (cut it in shorter segments and assembling the results after, output individual PNGs and make them into a video, etc)

**Comment by andypotato** [comment]
I'm only using it for upscaling images. The issue I am seeing is a very high RAM usage after about 60-70 individual upscales. The machine then spirals into swapping death. Pretty sure there is some memory leaking going on.

**Comment by overallbit** [comment]
You all can use my fork, I fixed it:

https://github.com/overallbit/Nvidia_RTX_Nodes_ComfyUI
